### ISSUE TITLE
[BUG] Rendering Flower Pot Crash

### ISSUE THREAD

**Issue by Fealtous** [Cristelknight999/DoAPI#22]
### What mod appears to be problematic?

🌲 BloomingNature

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is the mod running in an unstable environment?

- [X] I am using a supported modloader (Forge, Fabric, Quilt)
- [ ] I have self built the mod
- [ ] This is running in a dev environment

### Current Behavior

I'm actually here on behalf of a user that visited the Forge discord. As per their wording: "it was working before, but about 15 mins in I get kicked straight after joining." There aren't any incompatibilities listed on the curseforge page, so it's unclear if this is due to other mods or an actual problem in the rendering API provided. The trace doesn't implicate any other mods either.

Please let me know if you need any additional information and I'll do what I can to provide it.

<https://gist.githubusercontent.com/RealMangoBot/202b58355b46d84cb4365fc318aac508/raw/4897daaffdcffe58ca994756335569db2f7fc48c/latest_1_1.log>

<https://gist.githubusercontent.com/RealMangoBot/0b655361f7c40f9063874198ee69e995/raw/59f91ae83f88950419591a8c78fd22afb5bd6bed/debug_1_1.log>

### Relevant log output

```shell
net.minecraft.ReportedException: Rendering Block Entity
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:111) ~[client-1.20.1-20230612.114412-srg.jar%23250!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:79) ~[client-1.20.1-20230612.114412-srg.jar%23250!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1262) ~[client-1.20.1-20230612.114412-srg.jar%23250!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23250!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23250!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23250!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23250!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.30.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?]
	at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[client-1.20.1-20230612.114412-srg.jar%23250!/:?]
	at de.cristelknight.doapi.client.render.block.storage.FlowerPotBigRenderer.render(FlowerPotBigRenderer.java:20) ~[letsdo-API-forge-1.2.10-forge.jar%23225!/:?]
	at de.cristelknight.doapi.client.render.block.storage.api.StorageBlockEntityRenderer.render(StorageBlockEntityRenderer.java:52) ~[letsdo-API-forge-1.2.10-forge.jar%23225!/:?]
	at de.cristelknight.doapi.client.render.block.storage.api.StorageBlockEntityRenderer.m_6922_(StorageBlockEntityRenderer.java:17) ~[letsdo-API-forge-1.2.10-forge.jar%23225!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:90) ~[client-1.20.1-20230612.114412-srg.jar%23250!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112297_(BlockEntityRenderDispatcher.java:79) ~[client-1.20.1-20230612.114412-srg.jar%23250!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23250!/:?]
	... 22 more
```

### What modloader are you running the mod on?

Forge

**Comment by Cristelknight** [comment]
Was that flower pot from bloomingnature, or an other let‘s do mod?

**Comment by Cristelknight** [comment]
i think this is an easy fix. don’t know exactly when the next update will be released

**Comment by Cristelknight** [comment]
should be fixed
