### ISSUE TITLE
[BUG] Couldn't read config.json5

### ISSUE THREAD

**Issue by gqrshy** [Cristelknight999/DoAPI#24]
### What mod appears to be problematic?

🌲 BloomingNature

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is the mod running in an unstable environment?

- [X] I am using a supported modloader (Forge, Fabric, Quilt)
- [ ] I have self built the mod
- [ ] This is running in a dev environment

### Relevant log output

```shell
---- Minecraft Crash Report ----

// Hi. I'm Connector, and I'm a crashaholic
=========================
SINYTRA CONNECTOR IS PRESENT!
Please verify issues are not caused by Connector before reporting them to mod authors.
If you're unsure, file a report on Connector's issue tracker found at https://github.com/Sinytra/Connector/issues.
=========================

// Shall we play a game?

Time: 2024-05-07 06:58:47
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.2.30-universal.jar%23658!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectormod.mixins.json:CrashReportExtenderMixin from mod connectormod,pl:mixin:A}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.2.30-universal.jar%23658!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23653!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.30.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.30.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.30.jar%2369!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mod: 
	[Let's Do] API (doapi), Version: 1.2.11
		at TRANSFORMER/doapi@1.2.11/de.cristelknight.doapi.config.jankson.ConfigUtil.readConfig(ConfigUtil.java:42)
Stacktrace:
	at de.cristelknight.doapi.config.jankson.ConfigUtil.readConfig(ConfigUtil.java:42) ~[letsdo-API-forge-1.2.11-forge.jar%23512!/:?] {re:classloading}
-- MOD meadow --
Details:
	Mod File: /C:/Server/PekoCraft/mods/letsdo-meadow-forge-1.3.10.jar
	Failure message: [Let's Do] Meadow (meadow) has failed to load correctly
		java.lang.IllegalArgumentException: [Do Api] Couldn't read C:\Server\PekoCraft\config\meadow\config.json5, crashing instead. Maybe try to delete the config files!
	Mod Version: 1.3.10
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.IllegalArgumentException: [Do Api] Couldn't read C:\Server\PekoCraft\config\meadow\config.json5, crashing instead. Maybe try to delete the config files!
Stacktrace:
	at de.cristelknight.doapi.config.jankson.ConfigUtil.readConfig(ConfigUtil.java:42) ~[letsdo-API-forge-1.2.11-forge.jar%23512!/:?] {re:classloading}
	at de.cristelknight.doapi.config.jankson.config.CommentedConfig.readConfig(CommentedConfig.java:53) ~[letsdo-API-forge-1.2.11-forge.jar%23512!/:?] {re:mixin,re:classloading}
	at de.cristelknight.doapi.config.jankson.config.CommentedConfig.getConfig(CommentedConfig.java:43) ~[letsdo-API-forge-1.2.11-forge.jar%23512!/:?] {re:mixin,re:classloading}
	at de.cristelknight.doapi.config.jankson.config.CommentedConfig.getConfig(CommentedConfig.java:33) ~[letsdo-API-forge-1.2.11-forge.jar%23512!/:?] {re:mixin,re:classloading}
	at net.satisfyu.meadow.config.MeadowConfig.get(MeadowConfig.java:57) ~[letsdo-meadow-forge-1.3.10.jar%23518!/:?] {re:classloading}
	at net.satisfyu.meadow.Meadow.init(Meadow.java:18) ~[letsdo-meadow-forge-1.3.10.jar%23518!/:?] {re:classloading}
	at net.satisfyu.meadow.forge.MeadowForge.<init>(MeadowForge.java:25) ~[letsdo-meadow-forge-1.3.10.jar%23518!/:?] {re:classloading}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.30.jar%23655!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.30.jar%23654!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
```

### What modloader are you running the mod on?

Forge

**Comment by Cristelknight** [comment]
and it keeps crashing after deleting the file? and are you using other let‘s do mods?

**Comment by gqrshy** [comment]
Yes 
We have also installed many other letsdo mods. I have deleted the config file and it won't start.

**Comment by Cristelknight** [comment]
try to downgrade your meadow version (to 1.3.9) and then delete the config file before every start. that seemed to work for someone. or wait until a proper fix is released

**Comment by Cristelknight** [comment]
i just saw there is another verison releases 1.3.11. maybe it fixes that?
i‘m not at home so i can‘t really help today

**Comment by gqrshy** [comment]
I downloaded meadow 1.3.12 and it is now activated, although I need to delete config.json5!
Thanks for the quick update!

**Comment by FlyonDE** [comment]
I have the same problem with the [Let's Do] Vinery and [Let's Do] Meadow mods. If I delete the Conifgs of both of these two mods after the server fails to start and then start the server, everything works without any problems. But as soon as I stop and start the server again, the start fails again and I then have to delete the configs again. That can't be the point and makes using the mods on a server realistically impossible. I can't delete the configs every time the server starts.

Addition: The problem probably only occurs when you add or remove mods from the server. (When making changes to the mod folder.)

**Comment by Cristelknight** [comment]
Does this now work for everyone?
